### DISCUSSION TITLE
Integration of FEniCS with this optimization

### DISCUSSION THREAD

**Discussion by SMzubairshah** [CM2S/piglot#34] [Q&A] [answered]
Hi
I am integrating the Fenics as a numerical solver and for optimization using PIGLOT  so i started with linear elastic problem to identify the one parameter. (later into my original problem)
 I install it in the fenics environment already.
 Like the code is here in python for the optimization as given by general. SO i want to modify it according to mine.
```
import os
import shutil
from piglot.parameter import ParameterSet
from piglot.solver.solver import Case
from piglot.solver.curve.solver import CurveSolver
from piglot.solver.curve.fields import CurveInputData, Curve
from piglot.objectives.fitting import Reference, MSE
from piglot.objectives.fitting import FittingObjective, FittingSolver
from piglot.optimisers.botorch.bayes import BayesianBoTorch

# Set up output and temporary directories
output_dir = 'config'
tmp_dir = os.path.join(output_dir, 'tmp')
if os.path.isdir(output_dir):
    shutil.rmtree(output_dir)
os.makedirs(output_dir, exist_ok=True)

# Set up optimisation parameters
parameters = ParameterSet()
parameters.add('a', 1.0, 0.0, 4.0)

# Set up the reference
reference = Reference('output.txt', ['case_1'], output_dir)

**# Set up the solver to use
input_data = CurveInputData('case_1', '<a> * x ** 2', 'x', (-5.0, 5.0), 100)
case_1 = Case(input_data, {'case_1': Curve()})
solver = CurveSolver([case_1], parameters, output_dir, tmp_dir=tmp_dir)**

# Set up the fitting objective
references = {reference: ['case_1']}
fitting_solver = FittingSolver(solver, references)
objective = FittingObjective(parameters, fitting_solver, output_dir, MSE())

# Set up the optimiser and run optimisation
optimiser = BayesianBoTorch(objective)
value, params = optimiser.optimise(10, parameters, output_dir)
print(f"Optimal value: {value}")
print(f"Optimal parameters: {params}")


```
if i made a function of elastic problem elastic_beam(mu) with mu is the parameter. so should i remove the bold solver setup and just place the fenics function which is giving the stresses.

Should The output of the numerical solver be equal to or greater than two columns?

**Comment by ruicoelhopedro** [comment]
Hello! Thank you for your interest in using piglot!

Currently, the guide for implementing a new solver can be found [here](https://piglot.readthedocs.io/en/latest/solvers/solvers.html), which can be easily adapted to your use case by calling your `elastic_beam(mu)` in the `_solve()` method. However, we have recognised the over-complexity in the solver specification, and we have planned to simplify this interface in the next developments.

Additionally, we can implement an alternative version using a small wrapper solver around your existing function. This will also be helpful for other users. If you wish, we can quickly get this variant working for you to try.


Regarding the output, `piglot` expects instances of the `OutputResult` and `CaseResult` classes, which contain the numerical response for a given parameter set. Inside the `OutputResult`, there should be time and data arrays, which can be interpreted and the x and y values of the response.

**Reply by ruicoelhopedro** [reply, marked as answer]
> Additionally, we can implement an alternative version using a small wrapper solver around your existing function. This will also be helpful for other users. If you wish, we can quickly get this variant working for you to try.

We got a quick version of this feature in the branch [`script_solver`](https://github.com/CM2S/piglot/tree/script_solver). To test it, we used the following files:

- `config.yaml`:
```
iters: 10

optimiser: botorch

parameters:
  a: [0, -4, 4]
  b: [0, -4, 4]
  c: [0, -4, 4]

objective:
  name: design
  solver:
    name: script
    cases:
      'case_1':
        script: test.py
        class: TestScript
  targets:
    'minimum_value':
      quantity: max
      prediction: ['case_1']
      negate: False
    'maximum_area':
      quantity: integral
      prediction: ['case_1']
      negate: True
```
- `test.py`:
```
import numpy as np
from piglot.solver.solver import OutputResult
from piglot.solver.script.fields import ScriptCallable


class TestScript(ScriptCallable):
    """Test for the callable function to use as the solver."""

    def __call__(self, x: np.ndarray, tmp_dir: str) -> OutputResult:
        """Evaluate the function for the given point.

        Parameters
        ----------
        x : np.ndarray
            Point to evaluate the response for.
        tmp_dir : str
            Temporary directory to run the analyses.

        Returns
        -------
        OutputResult
            Response of the solver for the given point.
        """
        a = x[0]
        b = x[1]
        c = x[2]
        t = np.linspace(-2, 2, 100)
        values = abs(a * np.exp(t) + b * np.square(t) + c * np.sin(t))
        return OutputResult(t, values)
```

You can adapt this to your use case by calling your function in the `__call__` method in the `test.py` script. Put both files in the same directory and run `piglot` from it.

**Comment by ruicoelhopedro** [comment]
Sorry for the delay! The refactoring is in progress, and we may have a minimally functional version of the next interface. I have pushed the WIP to [`solver_refactoring`](https://github.com/CM2S/piglot/tree/solver_refactoring), so you can take a peek.

There is also a new script-based solver that is a bit simpler as well. Quick example:

- `config.yaml`
```
iters: 10

optimiser: botorch

parameters:
  frequency: [1, 0, 2]

objective:
  name: fitting
  solver:
    name: script
    script: sample_solver.py
    class: SampleSolver
  references:
    'sine.txt':
      prediction: ['sine']
```
- `sample_solver.py`
```
from typing import Dict, List
import numpy as np
from piglot.solver.script_solver import ScriptSolverCallable, OutputResult


class SampleSolver(ScriptSolverCallable):

    @staticmethod
    def get_output_fields() -> List[str]:
        return ["sine"]

    @staticmethod
    def solve(values: Dict[str, float]) -> Dict[str, OutputResult]:
        time = np.linspace(0, 1, 100)
        sine = np.sin(2 * np.pi * time * values["frequency"])
        return {
            "sine": OutputResult(time, sine),
        }
```
- `sine.txt`
```
0.0 0.0
0.5 1.0
1.0 0.0
```
