### ISSUE TITLE
examples/abaqus_solver_fitting something get wrong, may be bugs?

### ISSUE THREAD

**Issue by QamarQQ** [CM2S/piglot#36]
Hello, guys, thanks for your excellent project that give me a new light for my research items.

Recently, I try to use your latest version V0.4.0 to run the example in path "examples/abaqus_solver_fitting", but I have received this error
![bug](https://github.com/user-attachments/assets/095b65bc-8ab3-48f4-9d02-478285a4cbe7)

I don't know how to fix this error, may be bugs?  I hope someone can be help me. Thanks in advance. 
 
PS: 
<img width="475" alt="bug1" src="https://github.com/user-attachments/assets/2f7ccc68-da7b-4fde-9521-5e954dfdc363">
should be revised into:
```python

    nodeset_name = find_case_insensitive_key(
        variables["set_name"],
        list(odb.rootAssembly.nodeSets.keys()),)
```
because your provided sample.inp doesn't have 'REF_SET' in Instance.

**Comment by tmnp19** [comment]
Dear @QamarQQ,

Thank you for bringing this issue to my attention. It is indeed a bug, and I have identified the source of the problem. I am currently working on a fix and expect it to be resolved and ready for use later today. I appreciate your report and your patience.

Please do not hesitate to reach out if you have any further questions or need additional assistance.

Best regards,
Tiago Pires

**Comment by tmnp19** [comment]
The bug is already fixed. You can already use the latest version to run the Abaqus example. You should have an output that looks like this:

![image](https://github.com/user-attachments/assets/0dc42d9f-15f3-40a9-aea2-7811b23525ca)

I will be waiting for your feedback to close this issue.

**Comment by tmnp19** [comment]
Thank you so much @QamarQQ. It is very appreciated. Regarding your suggestion, in the near future, we will release a significant update that includes multi-objective optimisation and additional features. Following this update, we can provide a few more examples for Abaqus. Currently, for public FEM solvers, we only have an interface for Abaqus, as we primarily use our in-house FEM solver.

**Comment by tmnp19** [comment]
Dear @QamarQQ, first of all, let me apologize for taking so long to answer your comments.
Regarding your first comment, our multi-objective branch is not merged with `main` yet but it is already working. You can use the `composite_design_mo` branch to solve your multi-objective problems with Abaqus. 
Regarding your second comment, in order to run two cases you should add another case in the `cases:` field.
A multi-objective input file for Abaqus should be something like this:

```
parameters: #  set your parameters here

iters: 32

optimiser:
  name: botorch
  pca_variance: 1e-6 # Check the pre-print for further information on this
  reference_point: [0.58, 0] # This is an optional field and it represents the worst 
  # possible value that your objectives can take. If you are maximising the worst value
  # would be the minimum and vice-versa. If you know this values I recommend you to use
  # this field. 0.58 and 0 are set just as an example in here.

objective:
  name: design
  multi_objective: True
  composite: True
  solver:
    name: abaqus
    abaqus_path: # your Abaqus path
    cases:
      'sample.inp':
        step_name: Step-1
        instance_name: Part-1-1
        fields:
          'reaction_1':
            name: FieldsOutput
            set_name: RF_SET
            field: RF
            x_field: U
            direction: x
          'reaction_2':
            name: FieldsOutput
            set_name: RF_SET
            field: S
            x_field: LE
            direction: x

  targets:
    'target_1':
      quantity: integral
      prediction: ['reaction_1']
      # To perform a maximisation problem, set negate to True. By default False.
      negate: False
      n_points: 100 # Check the pre-print for further information on this
    'target_2':
      # Target quantity: using a script to compute a custom quantity
      quantity:
        name: script
        script: quantity_script.py # Path to the script
        class: QuantityClass # Class name (must be derived from Quantity)
      prediction: ['reaction_2']
      negate: True
      n_points: 100 # Check the pre-print for further information on this
```

The pre-print of our recent work that might be helpful for you is available in the following link: https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4920661

I hope this was helpful, let me know if you have any problems with the multi-objective optimisation.
